/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chanbarbosa.activityno1;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class CipherForm extends javax.swing.JFrame {

	/**
	 * Creates new form CipherForm
	 */
	
	Color defaultcolor, clickedcolor, white, clickedcolor1, clickedcolor2;
	public CipherForm() {
		initComponents();
		defaultcolor = new Color(153, 255, 255);
		clickedcolor = new Color(255,153,102);
		clickedcolor1 = new Color(153,255,153);
		clickedcolor2 = new Color(153,204,255);
		white = new Color(255, 255, 255);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

                jScrollPane3 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel4 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                p1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                p2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                p3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jPanel6 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                monoPanel = new javax.swing.JPanel();
                jPanel10 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                key1 = new javax.swing.JTextArea();
                jScrollPane2 = new javax.swing.JScrollPane();
                pt1 = new javax.swing.JTextArea();
                decrypt1 = new javax.swing.JButton();
                encrypt1 = new javax.swing.JButton();
                clear1 = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                output1 = new javax.swing.JTextArea();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel25 = new javax.swing.JLabel();
                polyPanel = new javax.swing.JPanel();
                jPanel11 = new javax.swing.JPanel();
                jScrollPane8 = new javax.swing.JScrollPane();
                key2 = new javax.swing.JTextArea();
                jScrollPane12 = new javax.swing.JScrollPane();
                pt2 = new javax.swing.JTextArea();
                dencrypt2 = new javax.swing.JButton();
                encrypt2 = new javax.swing.JButton();
                clear2 = new javax.swing.JButton();
                jScrollPane13 = new javax.swing.JScrollPane();
                output2 = new javax.swing.JTextArea();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                vigenerPanel = new javax.swing.JPanel();
                jPanel12 = new javax.swing.JPanel();
                jScrollPane14 = new javax.swing.JScrollPane();
                key3 = new javax.swing.JTextArea();
                jScrollPane15 = new javax.swing.JScrollPane();
                pt3 = new javax.swing.JTextArea();
                decrypt3 = new javax.swing.JButton();
                encrypt3 = new javax.swing.JButton();
                clear3 = new javax.swing.JButton();
                jScrollPane16 = new javax.swing.JScrollPane();
                output3 = new javax.swing.JTextArea();
                jLabel20 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jLabel22 = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jLabel27 = new javax.swing.JLabel();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane3.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel4.setBackground(new java.awt.Color(204, 255, 255));
                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel9.setBackground(new java.awt.Color(153, 255, 255));
                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(0, 0, 0));
                jLabel9.setText("Activity 1. Encryption");
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 270, 30));

                jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

                jPanel2.setBackground(new java.awt.Color(153, 255, 255));
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                p1.setBackground(new java.awt.Color(255, 153, 102));
                p1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                p1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                p1MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                p1MousePressed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                jLabel1.setText("Mono-Alphabetic Cipher");
                jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel1MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel1MousePressed(evt);
                        }
                });

                javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
                p1.setLayout(p1Layout);
                p1Layout.setHorizontalGroup(
                        p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                );
                p1Layout.setVerticalGroup(
                        p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(19, 19, 19))
                );

                jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 50));

                p2.setBackground(new java.awt.Color(153, 255, 255));
                p2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                p2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                p2MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                p2MousePressed(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 0, 0));
                jLabel2.setText("Poly-Alphabetic Cipher");
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel2MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel2MousePressed(evt);
                        }
                });

                javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
                p2.setLayout(p2Layout);
                p2Layout.setHorizontalGroup(
                        p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                );
                p2Layout.setVerticalGroup(
                        p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 50));

                p3.setBackground(new java.awt.Color(153, 255, 255));
                p3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                p3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                p3MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                p3MousePressed(evt);
                        }
                });

                jLabel3.setBackground(new java.awt.Color(204, 204, 204));
                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 0, 0));
                jLabel3.setText("Vigener Cipher");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jLabel3MousePressed(evt);
                        }
                });

                javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
                p3.setLayout(p3Layout);
                p3Layout.setHorizontalGroup(
                        p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                                .addGap(0, 64, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                p3Layout.setVerticalGroup(
                        p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)
                                .addContainerGap(16, Short.MAX_VALUE))
                );

                jPanel2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 50));

                jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 3, 12)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(0, 0, 0));
                jLabel8.setText("BSIT-AI41");
                jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

                jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 3, 12)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                jLabel10.setText("Created by: Christian Barbosa");
                jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

                jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\CIPHER.png")); // NOI18N
                jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

                jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\hecker.png")); // NOI18N
                jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 140));

                jPanel5.setBackground(new java.awt.Color(0, 255, 204));

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 190, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, -1));

                jPanel6.setBackground(new java.awt.Color(0, 255, 204));

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 210, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 210));

                jPanel7.setBackground(new java.awt.Color(0, 255, 204));

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 210, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                jPanel8.setBackground(new java.awt.Color(0, 255, 204));

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 190, Short.MAX_VALUE)
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

                jLabel13.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\lock (1).png")); // NOI18N
                jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, -1));

                jPanel9.setBackground(new java.awt.Color(0, 255, 204));

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 190, Short.MAX_VALUE)
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, -1));

                jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 560));

                jPanel10.setBackground(new java.awt.Color(255, 153, 102));
                jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                key1.setColumns(20);
                key1.setRows(5);
                jScrollPane1.setViewportView(key1);

                jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 57));

                pt1.setColumns(20);
                pt1.setRows(5);
                jScrollPane2.setViewportView(pt1);

                jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 430, 57));

                decrypt1.setBackground(new java.awt.Color(153, 255, 153));
                decrypt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                decrypt1.setText("Decrypt");
                decrypt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                decrypt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                decrypt1ActionPerformed(evt);
                        }
                });
                jPanel10.add(decrypt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 125, 39));

                encrypt1.setBackground(new java.awt.Color(51, 153, 255));
                encrypt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                encrypt1.setText("Encrypt");
                encrypt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                encrypt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                encrypt1ActionPerformed(evt);
                        }
                });
                jPanel10.add(encrypt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 125, 39));

                clear1.setBackground(new java.awt.Color(255, 0, 51));
                clear1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                clear1.setText("Clear");
                clear1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                clear1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clear1ActionPerformed(evt);
                        }
                });
                jPanel10.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 125, 39));

                output1.setEditable(false);
                output1.setColumns(20);
                output1.setRows(5);
                jScrollPane4.setViewportView(output1);

                jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 430, 57));

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 0, 255));
                jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\keys.png")); // NOI18N
                jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 220, 70, 37));

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 0, 255));
                jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\output.png")); // NOI18N
                jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 37));

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(0, 0, 255));
                jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\plaintext.png")); // NOI18N
                jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 37));

                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(0, 0, 153));
                jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\Mono.png")); // NOI18N
                jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 450, 40));

                jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\corner (1).png")); // NOI18N
                jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

                jLabel25.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\OverSizeCops\\corner2.png")); // NOI18N
                jLabel25.setText("jLabel25");
                jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 260, 250));

                javax.swing.GroupLayout monoPanelLayout = new javax.swing.GroupLayout(monoPanel);
                monoPanel.setLayout(monoPanelLayout);
                monoPanelLayout.setHorizontalGroup(
                        monoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                monoPanelLayout.setVerticalGroup(
                        monoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Mono", monoPanel);

                jPanel11.setBackground(new java.awt.Color(153, 255, 153));
                jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                key2.setColumns(20);
                key2.setRows(5);
                jScrollPane8.setViewportView(key2);

                jPanel11.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 57));

                pt2.setColumns(20);
                pt2.setRows(5);
                jScrollPane12.setViewportView(pt2);

                jPanel11.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 430, 57));

                dencrypt2.setBackground(new java.awt.Color(153, 255, 153));
                dencrypt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                dencrypt2.setText("Decrypt");
                dencrypt2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                dencrypt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dencrypt2ActionPerformed(evt);
                        }
                });
                jPanel11.add(dencrypt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 125, 39));

                encrypt2.setBackground(new java.awt.Color(51, 153, 255));
                encrypt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                encrypt2.setText("Encrypt");
                encrypt2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jPanel11.add(encrypt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 125, 39));

                clear2.setBackground(new java.awt.Color(255, 0, 51));
                clear2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                clear2.setText("Clear");
                clear2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                clear2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clear2ActionPerformed(evt);
                        }
                });
                jPanel11.add(clear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 125, 39));

                output2.setEditable(false);
                output2.setColumns(20);
                output2.setRows(5);
                jScrollPane13.setViewportView(output2);

                jPanel11.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 430, 57));

                jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(0, 0, 255));
                jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\keys.png")); // NOI18N
                jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 37));

                jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel17.setForeground(new java.awt.Color(0, 0, 255));
                jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\output.png")); // NOI18N
                jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 37));

                jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(0, 0, 255));
                jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\plaintext.png")); // NOI18N
                jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 37));

                jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel19.setForeground(new java.awt.Color(0, 0, 153));
                jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\poly.png")); // NOI18N
                jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 450, 40));

                jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\corner (1).png")); // NOI18N
                jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

                jLabel26.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\OverSizeCops\\corner2.png")); // NOI18N
                jLabel26.setText("jLabel25");
                jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 260, 250));

                javax.swing.GroupLayout polyPanelLayout = new javax.swing.GroupLayout(polyPanel);
                polyPanel.setLayout(polyPanelLayout);
                polyPanelLayout.setHorizontalGroup(
                        polyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(polyPanelLayout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                polyPanelLayout.setVerticalGroup(
                        polyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(polyPanelLayout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Poly", polyPanel);

                jPanel12.setBackground(new java.awt.Color(153, 204, 255));
                jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                key3.setColumns(20);
                key3.setRows(5);
                jScrollPane14.setViewportView(key3);

                jPanel12.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 57));

                pt3.setColumns(20);
                pt3.setRows(5);
                jScrollPane15.setViewportView(pt3);

                jPanel12.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 430, 57));

                decrypt3.setBackground(new java.awt.Color(153, 255, 153));
                decrypt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                decrypt3.setText("Decrypt");
                decrypt3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                decrypt3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                decrypt3ActionPerformed(evt);
                        }
                });
                jPanel12.add(decrypt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 125, 39));

                encrypt3.setBackground(new java.awt.Color(51, 153, 255));
                encrypt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                encrypt3.setText("Encrypt");
                encrypt3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                encrypt3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                encrypt3ActionPerformed(evt);
                        }
                });
                jPanel12.add(encrypt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 125, 39));

                clear3.setBackground(new java.awt.Color(255, 0, 51));
                clear3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                clear3.setText("Clear");
                clear3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                clear3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clear3ActionPerformed(evt);
                        }
                });
                jPanel12.add(clear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 125, 39));

                output3.setEditable(false);
                output3.setColumns(20);
                output3.setRows(5);
                jScrollPane16.setViewportView(output3);

                jPanel12.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 430, 57));

                jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel20.setForeground(new java.awt.Color(0, 0, 255));
                jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\keys.png")); // NOI18N
                jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, 37));

                jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel21.setForeground(new java.awt.Color(0, 0, 255));
                jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\output.png")); // NOI18N
                jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 37));

                jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel22.setForeground(new java.awt.Color(0, 0, 255));
                jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\plaintext.png")); // NOI18N
                jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 37));

                jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel23.setForeground(new java.awt.Color(0, 0, 153));
                jLabel23.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\Vigener.png")); // NOI18N
                jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 280, 40));

                jLabel24.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\corner (1).png")); // NOI18N
                jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

                jLabel27.setIcon(new javax.swing.ImageIcon("D:\\Kdrama\\OverSizeCops\\corner2.png")); // NOI18N
                jLabel27.setText("jLabel25");
                jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 260, 250));

                javax.swing.GroupLayout vigenerPanelLayout = new javax.swing.GroupLayout(vigenerPanel);
                vigenerPanel.setLayout(vigenerPanelLayout);
                vigenerPanelLayout.setHorizontalGroup(
                        vigenerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                vigenerPanelLayout.setVerticalGroup(
                        vigenerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Vigener", vigenerPanel);

                jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 770, 610));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>                        

        private void decrypt1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                jTabbedPane1.setSelectedIndex(0);
        }                                        

        private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
                jTabbedPane1.setSelectedIndex(0);
        }                                    

        private void p1MouseClicked(java.awt.event.MouseEvent evt) {                                
                 jTabbedPane1.setSelectedIndex(0);
        }                               

        private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
                jTabbedPane1.setSelectedIndex(1);
        }                                    

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
                 jTabbedPane1.setSelectedIndex(2);
        }                                    

        private void p2MouseClicked(java.awt.event.MouseEvent evt) {                                
                 jTabbedPane1.setSelectedIndex(1);
        }                               

        private void p3MouseClicked(java.awt.event.MouseEvent evt) {                                
                jTabbedPane1.setSelectedIndex(2);
        }                               

        private void dencrypt2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
                // TODO add your handling code here:
        }                                         

        private void decrypt3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		   String plaintext = pt3.getText();
		   String keyword = key3.getText();
		   
		   String encryptedText3 = encrypt(plaintext, keyword);
		   output3.setText(encryptedText3);  
		   
		   String decryptedText3 = decrypt(encryptedText3, keyword);
		    output3.setText(plaintext);  
        }                                        

        private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
                pt1.setText("");
		key1.setText("");
		output1.setText("");
        }                                      

        private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
                pt2.setText("");
		key2.setText("");
		output2.setText("");
        }                                      

        private void clear3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
                pt3.setText("");
		key3.setText("");
		output3.setText("");
        }                                      

        private void encrypt1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

		
        }                                        

        private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {                                     
                p1.setBackground(clickedcolor);
		p2.setBackground(defaultcolor);
		p3.setBackground(defaultcolor);
        }                                    

        private void p1MousePressed(java.awt.event.MouseEvent evt) {                                
                p1.setBackground(clickedcolor);
		p2.setBackground(defaultcolor);
		p3.setBackground(defaultcolor);
        }                               

        private void p2MousePressed(java.awt.event.MouseEvent evt) {                                
              	p1.setBackground(defaultcolor);
		p2.setBackground(clickedcolor1);
	       	p3.setBackground(defaultcolor);
        }                               

        private void p3MousePressed(java.awt.event.MouseEvent evt) {                                
		p1.setBackground(defaultcolor);
		p2.setBackground(defaultcolor);
	       	p3.setBackground(clickedcolor2);
        }                               

        private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {                                     
              	p1.setBackground(defaultcolor);
		p2.setBackground(clickedcolor1);
	       	p3.setBackground(defaultcolor);
        }                                    

        private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {                                     
              	p1.setBackground(defaultcolor);
		p2.setBackground(defaultcolor);
	       	p3.setBackground(clickedcolor2);
        }                                    

        private void encrypt3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                   String plaintext = pt3.getText();
		   String keyword = key3.getText();
		   
		   String encryptedText3 = encrypt(plaintext, keyword);
		   output3.setText(encryptedText3);
		   
        }                                        

	/**
	 * @param args the command line arguments
	 */
	 public static String encrypt(String plaintext, String keyword) {
        StringBuilder encryptedText = new StringBuilder();
        plaintext = plaintext.toUpperCase();
        keyword = keyword.toUpperCase();

        for (int i = 0, j = 0; i < plaintext.length(); i++) {
            char c = plaintext.charAt(i);
            if (c >= 'A' && c <= 'Z') {
                int shift = keyword.charAt(j) - 'A';
                char encryptedChar = (char) (((c - 'A' + shift) % 26) + 'A');
                encryptedText.append(encryptedChar);
                j = (j + 1) % keyword.length();
            } else {
                encryptedText.append(c);
            }
        }

        return encryptedText.toString();
    }
	public static String decrypt(String encryptedText, String keyword) {
        StringBuilder decryptedText = new StringBuilder();
        encryptedText = encryptedText;
        keyword = keyword;

        for (int i = 0, j = 0; i < encryptedText.length(); i++) {
            char c = encryptedText.charAt(i);
            if (c >= 'A' && c <= 'Z') {
                int shift = keyword.charAt(j) - 'A';
                char decryptedChar = (char) (((c - 'A' - shift + 26) % 26) + 'A');
                decryptedText.append(decryptedChar);
                j = (j + 1) % keyword.length();
            } else {
                decryptedText.append(c);
            }
        }

        return decryptedText.toString();
    }
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CipherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CipherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CipherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CipherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CipherForm().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify                     
        private javax.swing.JButton clear1;
        private javax.swing.JButton clear2;
        private javax.swing.JButton clear3;
        private javax.swing.JButton decrypt1;
        private javax.swing.JButton decrypt3;
        private javax.swing.JButton dencrypt2;
        private javax.swing.JButton encrypt1;
        private javax.swing.JButton encrypt2;
        private javax.swing.JButton encrypt3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane12;
        private javax.swing.JScrollPane jScrollPane13;
        private javax.swing.JScrollPane jScrollPane14;
        private javax.swing.JScrollPane jScrollPane15;
        private javax.swing.JScrollPane jScrollPane16;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane8;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextArea key1;
        private javax.swing.JTextArea key2;
        private javax.swing.JTextArea key3;
        private javax.swing.JPanel monoPanel;
        private javax.swing.JTextArea output1;
        private javax.swing.JTextArea output2;
        private javax.swing.JTextArea output3;
        private javax.swing.JPanel p1;
        private javax.swing.JPanel p2;
        private javax.swing.JPanel p3;
        private javax.swing.JPanel polyPanel;
        private javax.swing.JTextArea pt1;
        private javax.swing.JTextArea pt2;
        private javax.swing.JTextArea pt3;
        private javax.swing.JPanel vigenerPanel;
        // End of variables declaration                   
}
